import type { Metadata } from "next";
import Link from "next/link"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "Elite Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Arial, sans-serif', margin: 0 }}>
        
        <nav style={{ 
          padding: "20px", 
          borderBottom: "1px solid #333", 
          display: "flex", 
          gap: "20px",
          background: "#111",
          color: "white"
        }}>
          <Link href="/">🏠 Home</Link>
          <Link href="/about">🏢 About</Link>
          <Link href="/dashboard">📊 Dashboard</Link>
          <Link href="/users" style={{ textDecoration: 'none', color: '#ccc' }}>👥 Users</Link>
        </nav>

        <main style={{ padding: "20px", minHeight: "80vh" }}>
          {children}
        </main>

        <footer style={{ padding: "20px", textAlign: "center", fontSize: "12px", color: "#666", borderTop: "1px solid #eee" }}>
          &copy; 2025 Elite Project. All rights reserved.
        </footer>

      </body>
    </html>
  );
}